<SelectableLabel>:
    id: SLabelID
    orientation: 'horizontal'
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
            # Rectangle:
            # pos: self.pos
            # size: self.size
    #AsyncImage:
     #   id: async_image_id
    Label:
        id: label_id

<RV>:
    viewclass: 'SelectableLabel'
    SelectableRecycleBoxLayout:
        default_size: None, dp(56)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        # multiselect: True
        touch_multiselect: True

BoxLayout:
    RV:
        id: RV_ID
